"""Vibe prompt bank — ~200 rare override templates (~5% of interactions).

These simulate a DJ user changing the vibe/energy mid-session.
Sampled deterministically using the shared RNG.
"""
import random


class VibePromptBank:
    """Singleton bank of ~200 vibe override prompt templates."""

    _instance = None
    _templates: list[str] = []

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._load_templates()
        return cls._instance

    def _load_templates(self) -> None:
        self._templates = [
            # Energy transitions
            "Let's bring the energy down a bit.",
            "Can we ramp up the intensity?",
            "I want something more chill.",
            "Hit me with something aggressive.",
            "Let's keep it mellow.",
            "Time to crank it up.",
            "Drop the tempo a bit.",
            "Pick up the pace.",
            "I need something in between.",
            "Let's go harder.",
            "Softer landing on this one.",
            # Genre shifts
            "Switch to something more house-influenced.",
            "Add some hip-hop flavor.",
            "Let's go deeper on the techno.",
            "I want more DnB vibes.",
            "Can we get more ambient?",
            "Bring in some jazz elements.",
            "Time for something cinematic.",
            "Let's get experimental.",
            "Keep it more traditional.",
            # Instrumentation
            "More bass, less drums.",
            "Let's lead with the synths.",
            "I want the piano to shine.",
            "Bring the vocals forward.",
            "Less reverb on everything.",
            "Let's add some texture.",
            "The guitar should be the star.",
            "Focus on the rhythm.",
            "Make it more atmospheric.",
            "Strip it down to basics.",
            # Mood
            "This is too dark, lighten it up.",
            "Make it more melancholic.",
            "I want something euphoric.",
            "Give it a darker edge.",
            "This feels too happy.",
            "Let's get moody.",
            "Time for something uplifting.",
            "Keep it introspective.",
            "More tension in the build.",
            "Release the pressure a bit.",
            # Structure
            "Let's make it more minimal.",
            "Go big and layered.",
            "I want a breakdown section.",
            "Let's go full drop.",
            "Add some transitions.",
            "Keep it one continuous flow.",
            "I want some silence between sections.",
            "Let's make it feel infinite.",
            "Short and punchy.",
            "Draw it out more.",
            # Timbre
            "More analog warmth.",
            "Make it sound digital.",
            "I want it gritty.",
            "Let's keep it clean.",
            "Add some distortion.",
            "Bring out the midrange.",
            "More high-end sparkle.",
            "Thick and warm.",
            "Let's get harsh.",
            "Softer, rounder sound.",
            # Groove
            "Swing it more.",
            "Lock into a straight groove.",
            "I want a halftime feel.",
            "Double-time energy.",
            "Let's groove.",
            "Make it more driving.",
            "I want it to bounce.",
            "Less predictable rhythm.",
            "The groove needs to breathe.",
            "Tighten up the rhythm.",
            # Innovation
            "Try something unexpected.",
            "Give me a wild card.",
            "I want something unique.",
            "Let's get weird.",
            "No rules, just vibe.",
            "Take a risk.",
            "I want something familiar but new.",
            "Surprise me.",
            "The usual but better.",
            "Let's innovate.",
            # Additional templates to reach ~200
            "Let's warm things up.",
            "Cool it down.",
            "I need more heat.",
            "Let's keep it cool.",
            "Bring the fire.",
            "Extinguish the flames.",
            "I want something smoky.",
            "Clean and bright.",
            "Let's get dirty.",
            "Squeaky clean.",
            "More retro vibes.",
            "Keep it modern.",
            "Let's go vintage.",
            "Futuristic sounds.",
            "Nostalgic but fresh.",
            "I miss this sound.",
            "This sound is ahead of its time.",
            "Let's go underground.",
            "Mainstream energy.",
            "Underground vibes.",
            "Above the radar.",
            "Let's get experimental.",
            "Play it safe.",
            "Risk it all.",
            "Calculated moves.",
            "Let's be bold.",
            "Subtle nuances.",
            "In your face.",
            "Behind the scenes.",
            "Front and center.",
            "Background vibes.",
            "Spotlight on.",
            "Let's fade out.",
            "Fade back in.",
            "Let's start fresh.",
            "Keep building.",
            "Time to stop.",
            "Never stop.",
            "One more round.",
            "Last call.",
            "New beginning.",
            "The end.",
            "Middle of nowhere.",
            "Back to start.",
            "Let's drift.",
            "Ground me.",
            "Take me higher.",
            "Bring me down.",
            "Level up.",
            "Power down.",
            "Reboot.",
            "Override.",
            "Default settings.",
            "Custom mode.",
            "Let's get complex.",
            "Keep it simple.",
            "One track mind.",
            "Layered depth.",
            "Surface level.",
            "Deep dive.",
            "Shallow end.",
            "The deep end.",
            "Wade in slowly.",
            "Jump right in.",
            "Test the waters.",
            "Calm before the storm.",
            "Weather the storm.",
            "After the rain.",
            "Before sunrise.",
            "Golden hour.",
            "Midnight vibes.",
            "Noon day sun.",
            "Dawn patrol.",
            "Dusk till dawn.",
            "All night long.",
            "Morning energy.",
            "Afternoon slump.",
            "Evening elegance.",
            "Late night session.",
            "Early bird special.",
            "Night owl vibes.",
            "Sunrise service.",
            "Sunset strip.",
            "High noon.",
            "Witching hour.",
            "Magic hour.",
            "Golden minute.",
            "Silver second.",
            "Platinum hits.",
            "Bronze age.",
            "Iron will.",
            "Steel strength.",
            "Copper tone.",
            "Gold standard.",
            "Silver lining.",
            "Lead the way.",
            "Follow the crowd.",
            "Forge your own path.",
            " march to your own beat.",
            "Stay in rhythm.",
            "Off beat.",
            "On the one.",
            "Two steps forward.",
            "One step back.",
            "Round and round.",
            "Spiral up.",
            "Spiral down.",
            "Linear progression.",
            "Circular flow.",
            "Sharp turn.",
            "Smooth curve.",
            "Zigzag energy.",
            "Straight line.",
            "Parallel universe.",
            "Opposite direction.",
            "Same wavelength.",
            "Frequency modulation.",
            "Amplitude up.",
            "Amplitude down.",
            "Resonance building.",
            "Static noise.",
            "Clear signal.",
            "Let's get fuzzy.",
            "Crystal clear.",
            "Let's distort.",
            "Pure signal.",
            "Let's chorus.",
            "Dry as a bone.",
            "Wet and wild.",
            "Dripping sound.",
            "Packed ice.",
            "Melting pot.",
            "Frozen moment.",
            "Heated debate.",
            "Cold feet.",
            "Warm embrace.",
            "Hot mess.",
            "Cool customer.",
            "Fired up.",
            "Burned out.",
            "Smoldering embers.",
            "Full blaze.",
            "Controlled burn.",
            "Wildfire.",
            "Campfire stories.",
            "City lights.",
            "Dark country road.",
            "Ocean breeze.",
            "Mountain air.",
            "Desert wind.",
            "Forest floor.",
            "Urban jungle.",
            "Concrete jungle.",
            "Glass house.",
            "Open field.",
            "Closed loop.",
            "Open door.",
            "Window of opportunity.",
            "Wall flower.",
            "Center stage.",
            "Back seat.",
            "Front row.",
            "Balcony view.",
            "Nosebleed section.",
            "Standing room only.",
            "Sold out.",
            "General admission.",
            "VIP treatment.",
            "Backstage pass.",
            "Green room.",
            "Main stage.",
            "Side stage.",
            "After party.",
            "Warm up act.",
            "Headliner.",
            "Encore performance.",
            "Opening remarks.",
            "Closing argument.",
            "Intermission.",
            "Marathon session.",
            "Sprint finish.",
            " marathon not a race.",
            "Slow burn.",
            "Fast forward.",
            "Rewind.",
            "Pause.",
            "Play.",
            "Stop.",
            "Record.",
            "Eject.",
            "Let's remix.",
            "Original version.",
            "Acoustic setting.",
            "Full production.",
            "Radio edit.",
            "Extended cut.",
            "Director's cut.",
            "Final draft.",
            "First draft.",
            "Working copy.",
            "Master take.",
            "B-side.",
            "A-side.",
            "Deep cut.",
            "Fan favorite.",
            "Hidden track.",
            "Bonus content.",
            "Deleted scenes.",
            "The vault.",
            "Exclusive release.",
            "Leaked track.",
            "Premiere.",
            "Limited run.",
            "Open ended.",
            "Tight closure.",
            "Loose ends.",
            "Wrapped up.",
            "Unfinished business.",
            "Work in progress.",
            "Final version.",
            "Beta test.",
            "Alpha release.",
            "Stable build.",
            "Nightly build.",
            "Rolling release.",
            "Long term support.",
            "End of life.",
            "New chapter.",
            "The sequel.",
            "Reboot.",
            "Spin off.",
            "Crossover event.",
            "Stand alone.",
            "Connected universe.",
            "Solo act.",
            "Band together.",
            "Jam session.",
            "The duet.",
            "Solo performer.",
            "Choir energy.",
            "Call and response.",
            "Solo journey.",
            "Group dynamics.",
            "The ensemble.",
            "Star power.",
            "Supporting role.",
            "Lead character.",
            "Narrator voice.",
            "Let's build tension.",
            "Release the tension.",
            "Maximum pressure.",
            "Zero pressure.",
            "Just right.",
            "Over the top.",
            "Under the radar.",
            "Middle ground.",
            "Edge of your seat.",
            "Back in the day.",
            "Future sounds.",
            "Present moment.",
            "Timeless classic.",
            "Of the moment.",
            "Ahead of its time.",
            "Behind the times.",
            "Cutting edge.",
            "Old school.",
            "New wave.",
            "Next generation.",
            "Heritage sound.",
            "Legacy status.",
            "Roots and branches.",
            "The trunk.",
            "New growth.",
            "Seasonal change.",
            "Evergreen.",
            "Autumn leaves.",
            "Spring forward.",
            "Winter is coming.",
            "Summer vibe.",
            "Fall colors.",
            "Spring renewal.",
            # Keep total around 200
        ]
        # Trim to approximately 200 templates
        self._templates = self._templates[:200]

    def sample(self, rng: random.Random) -> str:
        """Sample a random vibe prompt using the given RNG.

        The RNG determines which template is chosen, ensuring
        deterministic sampling when used with the shared RNG.
        """
        return rng.choice(self._templates)
